apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-{{ .Chart.Name }}
  labels:
    app: database
spec:
  selector:
    matchLabels:
      app: database
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: database
        tier: mysql
    spec:
      containers:
        - image: {{ include "database.image" . | quote }}
          name: mysql
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.configMap.dbname }}
      
            - name: MYSQL_USER
              value: {{ .Values.configMap.username }}
              
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-security
                  key: password
            - name: MYSQL_HOST
              value: {{ .Values.configMap.server }}
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-security
                  key: password
          ports:
            - containerPort: {{ .Values.database.containerPort }}
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-pvc