apiVersion: v1
kind: Service
metadata:
  name: helm-{{ .Chart.Name }}-service
  labels:
    app: database
spec:
  ports:
    - port: 3306
  selector:
    app: database
    tier: mysql
  clusterIP: None