apiVersion: v1
kind: Service
metadata:
  name: helm-{{ .Chart.Name }}-service
  labels:
    app: helm-{{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: backend
  ports:
    - protocol: TCP
      name: httpbackend
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      