name: "Terraform destroy"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform-destroy:
    name: "Terraform destroy"
    runs-on: ubuntu-latest
    environment:
      name: production-destroy
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Show Destroy plan
        run: terraform plan --destroy -lock=false -input=false
        continue-on-error: true
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Destroy resources jobs
        id: destroy
        run: terraform destroy -auto-approve -lock=false -input=false
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
